# Generated by Django 4.2.7 on 2023-11-22 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
    ]
